name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to 'main'
  pull_request:
    branches:
      - main  # Trigger on pull request to 'main'

jobs:
  build:
    runs-on: self-hosted  # Use the self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t node-app .

      - name: Run Docker container
        run: |
          docker run -d -p 3000:3000 node-app